version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: reclamation_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ahlem
      POSTGRES_DB: reclamation_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./reclamation
      dockerfile: Dockerfile
    container_name: reclamation_backend
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/reclamation_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ahlem
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  frontend:
    build:
      context: ./reclamationfrontend
      dockerfile: Dockerfile
    container_name: reclamation_frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pgdata:
